apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: "mydatabase"
  POSTGRES_USER: "myuser"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      index index.html index.htm;

      # SPA routing
      location / {
        try_files \$uri \$uri/ /index.html =404;
      }

      # Proxy API calls to Django
      location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
      }
    }
